pipeline {
    agent any

    environment {
        IMAGE_NAME = "roua211jft7404/novamind-backend"
        // ID des credentials DockerHub dans Jenkins
        DOCKER_CREDENTIALS = 'dockerhub'
        // ID des credentials GitHub dans Jenkins
        GIT_CREDENTIALS = 'Git'
    }

    stages {
        stage('Checkout') {
            steps {
                // Récupération du code depuis GitHub
                git branch: 'develop',
                    url: 'https://github.com/roua16/Devop.git',
                    credentialsId: "${GIT_CREDENTIALS}"
            }
        }

        stage('Docker Login') {
            steps {
                // Connexion à DockerHub avec credentials
                withCredentials([usernamePassword(credentialsId: "${DOCKER_CREDENTIALS}", usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
                }
            }
        }

        stage('Docker Build') {
            steps {
                // Build de l'image Docker
                sh 'docker build -t $IMAGE_NAME:$BUILD_NUMBER .'
                sh 'docker tag $IMAGE_NAME:$BUILD_NUMBER $IMAGE_NAME:latest'
            }
        }

        stage('Docker Push') {
            steps {
                // Push vers DockerHub
                sh 'docker push $IMAGE_NAME:$BUILD_NUMBER'
                sh 'docker push $IMAGE_NAME:latest'
            }
        }
    }

    post {
        success {
            echo '✅ Build et push Docker réussis !'
        }
        failure {
            echo '❌ Le pipeline a échoué. Vérifie les logs.'
        }
    }
}
